/** Límites calibrados al CV de referencia (1 página, Arial ~10pt). */
export const CV_LAYOUT = {
  page: {
    widthIn: 8.5,
    heightIn: 11,
    paddingTopIn: 0.65,
    paddingSideIn: 0.65,
    paddingBottomIn: 0.65,
  },
  typography: {
    fontFamily: 'Arial, Helvetica, sans-serif',
    namePt: 16,
    subtitlePt: 11,
    contactPt: 10,
    sectionTitlePt: 11,
    bodyPt: 10,
    lineHeight: 1.25,
  },
  theme: {
    accent: '#0018cc',
    text: '#1a1a1a',
    textMuted: '#666666',
    topBarHeightPx: 5,
  },
  sobreMi: {
    minChars: 170,
    maxChars: 310,
    maxWords: 52,
    minWords: 28,
    maxLines: 3,
    /** Ancho útil ≈ 7.2in @ Arial 10pt (calibrado al PDF). */
    charsPerLine: 104,
  },
  habilidades: {
    exactLines: 3,
    minLines: 2,
    maxCharsPerLine: 72,
    maxTotalChars: 210,
    minTotalChars: 40,
  },
  validationMaxAttempts: 8,
} as const;

export const CV_SECTION_LABELS = {
  es: {
    sobreMi: 'SOBRE MI',
    experiencia: 'EXPERIENCIA',
    educacion: 'EDUCACIÓN',
    habilidades: 'HABILIDADES',
    portafolio: 'Portafolio',
    github: 'GitHub',
    telefono: 'Telefono',
    correo: 'Correo',
    lenguajesProgramacion: 'Lenguajes de programación',
    idiomas: 'Idiomas',
  },
  en: {
    sobreMi: 'ABOUT ME',
    experiencia: 'EXPERIENCE',
    educacion: 'EDUCATION',
    habilidades: 'SKILLS',
    portafolio: 'Portfolio',
    github: 'GitHub',
    telefono: 'Phone',
    correo: 'Email',
    lenguajesProgramacion: 'Programming languages',
    idiomas: 'Languages',
  },
} as const;

/** Etiquetas del panel de edición — siempre en español (UI). */
export const CV_EDITOR_LABELS = {
  pdfFileName: 'Nombre del archivo PDF',
  pdfFileNameHint: 'Nombre (sin .pdf)',
  personalData: 'Datos personales',
  nombreLinea1: 'Nombre (línea 1)',
  nombreLinea2: 'Apellido (línea 2)',
  carrera: 'Carrera / título profesional',
  ubicacion: 'Ubicación',
  telefono: 'Teléfono',
  correo: 'Correo',
  portafolio: 'Portafolio',
  github: 'GitHub',
  sobreMi: 'Sobre mí',
  sobreMiTexto: 'Texto',
  sobreMiChars: 'caracteres · objetivo 170–310',
  refineSobre: 'Pedir cambio a la IA',
  refineSobrePlaceholder: 'Ej. enfatiza experiencia en backend…',
  refineSobreBtn: 'Regenerar sobre mí con IA',
  experiencia: 'Experiencia',
  expLugar: 'Empresa / lugar',
  expCargo: 'Cargo',
  expFechas: 'Fechas',
  expInicio: 'Inicio',
  expFin: 'Fin',
  expDescripcion: 'Descripción',
  educacion: 'Educación',
  eduInstitucion: 'Institución',
  eduTitulo: 'Título / programa',
  eduFechas: 'Fechas',
  eduNota: 'Nota / GPA',
  habilidades: 'Habilidades',
  skillLineTools: 'Habilidades / herramientas',
  skillLineProgramming: 'Lenguajes de programación',
  skillLineLanguages: 'Idiomas',
  refineSkills: 'Pedir cambio a la IA',
  refineSkillsPlaceholder: 'Ej. prioriza cloud y TypeScript…',
  refineSkillsBtn: 'Regenerar habilidades con IA',
} as const;
